# Configuration file for PDW simulator
scenario:
  start_time: 0.0
  end_time: 100.0
  time_step: 0.01

radars:
  - name: "Radar1" # High power radar with complex patterns
    power: 2000.0
    start_position: [100, 200]
    velocity: [10, 20]
    start_time: 10.0
    rotation_type: "constant"
    rotation_params:
      t0: 10.0
      alpha0: 9.99
      T_rot: 3.0
    pri_type: "switched"
    pri_params:
      pri_pattern: [0.0006, 0.0007, 0.0008]
      repetitions: [5, 5, 5]
    frequency_type: "switched"
    frequency_params:
      frequency_pattern: [9.2e9, 9.4e9, 9.6e9]
      repetitions: [5, 5, 5]
    pulse_width_type: "switched"
    pulse_width_params:
      pulse_width_pattern: [1.2e-6, 1.4e-6, 1.6e-6]
      repetitions: [5, 5, 5]
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 5.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -20.0

  - name: "Radar2" # Radar with jitter and varying rotation
    power: 1800.0
    start_position: [500, -300]
    velocity: [0, -10]
    start_time: 2.0
    rotation_type: "varying"
    rotation_params:
      t0: 2.0
      alpha0: 30.0
      T_rot: 2.5
      A: 0.5
      s: 1.0
      phi0: 0.0
    pri_type: "jitter"
    pri_params:
      mean_pri: 0.001
      jitter_percentage: 8.0
    frequency_type: "jitter"
    frequency_params:
      mean_frequency: 9.5e9
      jitter_percentage: 8.0
    pulse_width_type: "jitter"
    pulse_width_params:
      mean_pulse_width: 1.5e-6
      jitter_percentage: 8.0
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 4.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -22.0

  - name: "Radar3" # Fast moving radar with stagger patterns
    power: 2200.0
    start_position: [100, 200]
    velocity: [100, 10]
    start_time: 4.0
    rotation_type: "constant"
    rotation_params:
      t0: 0.0
      alpha0: 0.0
      T_rot: 2.0
    pri_type: "stagger"
    pri_params:
      pri_pattern: [0.0007, 0.0008, 0.0009, 0.001]
    frequency_type: "stagger"
    frequency_params:
      frequency_pattern: [9.3e9, 9.5e9, 9.7e9, 9.9e9]
    pulse_width_type: "stagger"
    pulse_width_params:
      pulse_width_pattern: [1.1e-6, 1.3e-6, 1.5e-6, 1.7e-6]
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 3.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -25.0

  - name: "Radar4" # High frequency radar with varying patterns
    power: 2500.0
    start_position: [-400, 300]
    velocity: [-15, 25]
    start_time: 0.0
    rotation_type: "varying"
    rotation_params:
      t0: 0.0
      alpha0: 45.0
      T_rot: 3.5
      A: 0.4
      s: 1.5
      phi0: 90.0
    pri_type: "switched"
    pri_params:
      pri_pattern: [0.0005, 0.0006, 0.0007]
      repetitions: [6, 6, 6]
    frequency_type: "switched"
    frequency_params:
      frequency_pattern: [10.0e9, 10.2e9, 10.4e9]
      repetitions: [6, 6, 6]
    pulse_width_type: "jitter"
    pulse_width_params:
      mean_pulse_width: 1.0e-6
      jitter_percentage: 10.0
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 2.5
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -28.0

  - name: "Radar5" # Low power, high precision radar
    power: 1000.0
    start_position: [800, -600]
    velocity: [-5, -5]
    start_time: 5.0
    rotation_type: "constant"
    rotation_params:
      t0: 5.0
      alpha0: 60.0
      T_rot: 4.0
    pri_type: "fixed"
    pri_params:
      pri: 0.0004
    frequency_type: "fixed"
    frequency_params:
      frequency: 9.8e9
    pulse_width_type: "fixed"
    pulse_width_params:
      pulse_width: 0.8e-6
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 2.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -30.0

sensors:
  - name: "Sensor1"
    start_position: [2000, 2000]
    velocity: [25, 10]
    start_time: 0.0
    saturation_level: "-70 dB"
    freq_padding_factor: 5
    detection_probability:
      level: [-75, -80, -85, -90]
      probability: [100, 90, 70, 50]
    amplitude_error:
      systematic:
        type: "linear"
        error: "0 dB"
        rate: "0.2 dB/s"
      arbitrary:
        type: "gaussian"
        error: "2 dB"
    toa_error:
      systematic:
        type: "constant"
        error: "0 s"
      arbitrary:
        type: "gaussian"
        error: "5e-9 s"
    frequency_error:
      systematic:
        type: "linear"
        error: "0 Hz"
        rate: "100 Hz/s"
      arbitrary:
        type: "uniform"
        error: "2e6 Hz"
    pulse_width_error:
      systematic:
        type: "constant"
        error: "0 s"
      arbitrary:
        type: "uniform"
        error: "5%"
    aoa_error:
      systematic:
        type: "constant"
        error: "0 deg"
      arbitrary:
        type: "gaussian"
        error: "2 deg"
