# Configuration file for PDW simulator
scenario:
  start_time: 0.0
  end_time: 100.0
  time_step: 0.01

radars:
  - name: "Radar1"
    power: 40.0 # In dBm
    start_position: [100, 200]
    velocity: [10, 20]
    start_time: 10.0
    rotation_type: "constant"
    rotation_params:
      t0: 10.0
      alpha0: 45.0 # In degrees (0-360)
      T_rot: 3.0
    pri_type: "switched"
    pri_params:
      pri_pattern: [0.0006, 0.0007, 0.0008]
      repetitions: [5, 5, 5]
    frequency_type: "switched"
    frequency_params:
      frequency_pattern: [1.500e9, 1.504e9, 1.508e9] # Each separated by 4MHz minimum
      repetitions: [5, 5, 5]
    pulse_width_type: "switched"
    pulse_width_params:
      pulse_width_pattern: [100.0e-6, 200.0e-6, 300.0e-6] # Within 100-500 microseconds
      repetitions: [5, 5, 5]
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 5.0
      radar_power_at_main_lobe: 0.0 # dBm
      radar_power_at_back_lobe: -20.0 # dBm

  - name: "Radar2"
    power: 55.0 # In dBm
    start_position: [500, -300]
    velocity: [0, -10]
    start_time: 2.0
    rotation_type: "varying"
    rotation_params:
      t0: 2.0
      alpha0: 180.0 # In degrees (0-360)
      T_rot: 2.5
      A: 0.5
      s: 1.0
      phi0: 0.0
    pri_type: "jitter"
    pri_params:
      mean_pri: 0.001
      jitter_percentage: 8.0
    frequency_type: "fixed"
    frequency_params:
      frequency: 1.512e9 # At least 4MHz from Radar1's highest frequency
    pulse_width_type: "jitter"
    pulse_width_params:
      mean_pulse_width: 250.0e-6 # Within 100-500 microseconds
      jitter_percentage: 8.0
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 4.0
      radar_power_at_main_lobe: 0.0 # dBm
      radar_power_at_back_lobe: -22.0 # dBm

  - name: "Radar3"
    power: 62.0 # In dBm
    start_position: [100, 200]
    velocity: [100, 10]
    start_time: 4.0
    rotation_type: "constant"
    rotation_params:
      t0: 0.0
      alpha0: 270.0 # In degrees (0-360)
      T_rot: 2.0
    pri_type: "stagger"
    pri_params:
      pri_pattern: [0.0007, 0.0008, 0.0009, 0.001]
    frequency_type: "stagger"
    frequency_params:
      frequency_pattern: [1.516e9, 1.520e9, 1.524e9, 1.528e9] # Each separated by 4MHz
    pulse_width_type: "stagger"
    pulse_width_params:
      pulse_width_pattern: [150.0e-6, 250.0e-6, 350.0e-6, 450.0e-6] # Within 100-500 microseconds
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 3.0
      radar_power_at_main_lobe: 0.0 # dBm
      radar_power_at_back_lobe: -25.0 # dBm

  - name: "Radar4"
    power: 58.0 # In dBm
    start_position: [-400, 300]
    velocity: [-15, 25]
    start_time: 0.0
    rotation_type: "varying"
    rotation_params:
      t0: 0.0
      alpha0: 90.0 # In degrees (0-360)
      T_rot: 3.5
      A: 0.4
      s: 1.5
      phi0: 90.0
    pri_type: "switched"
    pri_params:
      pri_pattern: [0.0005, 0.0006, 0.0007]
      repetitions: [6, 6, 6]
    frequency_type: "fixed"
    frequency_params:
      frequency: 1.532e9 # At least 4MHz from Radar3's highest frequency
    pulse_width_type: "jitter"
    pulse_width_params:
      mean_pulse_width: 400.0e-6 # Within 100-500 microseconds
      jitter_percentage: 10.0
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 2.5
      radar_power_at_main_lobe: 0.0 # dBm
      radar_power_at_back_lobe: -28.0 # dBm

  - name: "Radar5"
    power: 60.0 # In dBm
    start_position: [800, -600]
    velocity: [-5, -5]
    start_time: 5.0
    rotation_type: "constant"
    rotation_params:
      t0: 5.0
      alpha0: 60.0 # In degrees (0-360)
      T_rot: 4.0
    pri_type: "fixed"
    pri_params:
      pri: 0.0004
    frequency_type: "fixed"
    frequency_params:
      frequency: 1.536e9 # At least 4MHz from Radar4's frequency
    pulse_width_type: "fixed"
    pulse_width_params:
      pulse_width: 150.0e-6 # Within 100-500 microseconds
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 2.0
      radar_power_at_main_lobe: 0.0 # dBm
      radar_power_at_back_lobe: -30.0 # dBm

sensors:
  - name: "Sensor1"
    start_position: [2000, 2000]
    velocity: [25, 10]
    start_time: 0.0
    saturation_level: "-65 dBm" # Matches minimum amplitude range
    freq_padding_factor: 5
    detection_probability:
      level: [-65, -70, -75, -80] # In dBm
      probability: [100, 90, 70, 50]
    amplitude_error:
      systematic:
        type: "constant"
        error: "0 dBm"
      arbitrary:
        type: "gaussian"
        error: "2 dBm"
    toa_error:
      systematic:
        type: "constant"
        error: "0 s"
      arbitrary:
        type: "gaussian"
        error: "5e-9 s"
    frequency_error:
      systematic:
        type: "constant"
        error: "0 Hz"
      arbitrary:
        type: "gaussian"
        error: "1%" # Matches 1% accuracy specification
    pulse_width_error:
      systematic:
        type: "constant"
        error: "0 s"
      arbitrary:
        type: "gaussian"
        error: "25e-9 s" # Matches ±25 nanosecond specification
    aoa_error:
      systematic:
        type: "constant"
        error: "0 deg"
      arbitrary:
        type: "gaussian"
        error: "3.5 deg" # Within 2-5 degree specification
