# Configuration file for PDW simulator with validation constraints
scenario:
  start_time: 0.0
  end_time: 10.0
  time_step: 0.01

radars:
  - name: "Radar1" # High power radar with complex patterns
    power: 2000.0
    start_position: [100, 200]
    velocity: [10, 20]
    start_time: 10.0
    rotation_type: "constant"
    rotation_params:
      t0: 10.0
      alpha0: 9.99
      T_rot: 3.0
    pri_type: "switched"
    pri_params:
      pri_pattern: [0.0006, 0.0007, 0.0008]
      repetitions: [5, 5, 5]
    frequency_type: "switched"
    frequency_params:
      frequency_pattern: [1.5e9, 2.0e9, 2.5e9] # Changed to be within 0.5-40 GHz range with >4MHz separation
      repetitions: [5, 5, 5]
    pulse_width_type: "switched"
    pulse_width_params:
      pulse_width_pattern: [150e-6, 200e-6, 250e-6] # Changed to 150-250 microseconds
      repetitions: [5, 5, 5]
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 5.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -20.0

  - name: "Radar2"
    power: 1800.0
    start_position: [500, -300]
    velocity: [0, -10]
    start_time: 2.0
    rotation_type: "varying"
    rotation_params:
      t0: 2.0
      alpha0: 30.0
      T_rot: 2.5
      A: 0.5
      s: 1.0
      phi0: 0.0
    pri_type: "jitter"
    pri_params:
      mean_pri: 0.001
      jitter_percentage: 8.0
    frequency_type: "fixed"
    frequency_params:
      frequency: 3.0e9 # 3 GHz - within range
    pulse_width_type: "fixed"
    pulse_width_params:
      pulse_width: 300e-6 # 300 microseconds
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 4.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -22.0

  - name: "Radar3"
    power: 2200.0
    start_position: [100, 200]
    velocity: [100, 10]
    start_time: 4.0
    rotation_type: "constant"
    rotation_params:
      t0: 0.0
      alpha0: 0.0
      T_rot: 2.0
    pri_type: "stagger"
    pri_params:
      pri_pattern: [0.0007, 0.0008, 0.0009, 0.001]
    frequency_type: "stagger"
    frequency_params:
      frequency_pattern: [4.0e9, 5.0e9, 6.0e9, 7.0e9] # Changed to be within range with >4MHz separation
    pulse_width_type: "stagger"
    pulse_width_params:
      pulse_width_pattern: [200e-6, 250e-6, 300e-6, 350e-6] # Changed to microseconds range
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 3.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -25.0

  - name: "Radar4"
    power: 2500.0
    start_position: [-400, 300]
    velocity: [-15, 25]
    start_time: 0.0
    rotation_type: "varying"
    rotation_params:
      t0: 0.0
      alpha0: 45.0
      T_rot: 3.5
      A: 0.4
      s: 1.5
      phi0: 90.0
    pri_type: "switched"
    pri_params:
      pri_pattern: [0.0005, 0.0006, 0.0007]
      repetitions: [6, 6, 6]
    frequency_type: "switched"
    frequency_params:
      frequency_pattern: [8.0e9, 9.0e9, 10.0e9] # Changed to be within range
      repetitions: [6, 6, 6]
    pulse_width_type: "jitter"
    pulse_width_params:
      mean_pulse_width: 400e-6 # 400 microseconds
      jitter_percentage: 10.0
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 2.5
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -28.0

  - name: "Radar5"
    power: 1000.0
    start_position: [800, -600]
    velocity: [-5, -5]
    start_time: 5.0
    rotation_type: "constant"
    rotation_params:
      t0: 5.0
      alpha0: 60.0
      T_rot: 4.0
    pri_type: "fixed"
    pri_params:
      pri: 0.0004
    frequency_type: "fixed"
    frequency_params:
      frequency: 15.0e9 # 15 GHz - within range
    pulse_width_type: "fixed"
    pulse_width_params:
      pulse_width: 450e-6 # 450 microseconds
    lobe_pattern:
      type: "Sinc"
      main_lobe_opening_angle: 2.0
      radar_power_at_main_lobe: 0.0
      radar_power_at_back_lobe: -30.0

sensors:
  - name: "Sensor1"
    start_position: [2000, 2000]
    velocity: [25, 10]
    start_time: 0.0
    saturation_level: "-50 dB" # Changed to be within -65 to 0 dBm range
    freq_padding_factor: 5
    detection_probability:
      level: [-60, -62, -63, -64] # Changed to be within -65 to 0 dBm range
      probability: [100, 90, 70, 50]
    amplitude_error:
      systematic:
        type: "linear"
        error: "0 dB"
        rate: "0.2 dB/s"
      arbitrary:
        type: "gaussian"
        error: "2 dB"
    toa_error:
      systematic:
        type: "constant"
        error: "0 s"
      arbitrary:
        type: "gaussian"
        error: "25e-9 s" # Changed to match ±25ns accuracy requirement
    frequency_error:
      systematic:
        type: "linear"
        error: "0 Hz"
        rate: "100 Hz/s"
      arbitrary:
        type: "uniform"
        error: "2e6 Hz"
    pulse_width_error:
      systematic:
        type: "constant"
        error: "0 s"
      arbitrary:
        type: "uniform"
        error: "5%"
    aoa_error:
      systematic:
        type: "constant"
        error: "0 deg"
      arbitrary:
        type: "gaussian"
        error: "2 deg" # Within 2-5 degree accuracy requirement
