radars:
- frequency_params:
    frequency_pattern:
    - 1.500e9
    - 1.504e9
    - 1.508e9
    repetitions:
    - 5
    - 5
    - 5
  frequency_type: switched
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar1
  power: 40.0
  pri_params:
    pri_pattern:
    - 0.0006
    - 0.0007
    - 0.0008
    repetitions:
    - 5
    - 5
    - 5
  pri_type: switched
  pulse_width_params:
    pulse_width_pattern:
    - 0.0001
    - 0.0002
    - 0.0003
    repetitions:
    - 5
    - 5
    - 5
  pulse_width_type: switched
  rotation_params:
    T_rot: 3.0
    alpha0: 45.0
    t0: 10.0
  rotation_type: constant
  start_position:
  - 100
  - 200
  start_time: 10.0
  velocity:
  - 10
  - 20
scenario:
  end_time: 100.0
  start_time: 0.0
  time_step: 0.01
sensors:
- amplitude_error:
    arbitrary:
      error: 2 dBm
      type: gaussian
    systematic:
      error: 0 dBm
      type: constant
  aoa_error:
    arbitrary:
      error: 3.5 deg
      type: gaussian
    systematic:
      error: 0 deg
      type: constant
  detection_probability:
    level:
    - -65
    - -70
    - -75
    - -80
    probability:
    - 100
    - 90
    - 70
    - 50
  freq_padding_factor: 5
  frequency_error:
    arbitrary:
      error: 1%
      type: gaussian
    systematic:
      error: 0 Hz
      type: constant
  name: Sensor1
  pulse_width_error:
    arbitrary:
      error: 25e-9 s
      type: gaussian
    systematic:
      error: 0 s
      type: constant
  saturation_level: -65 dBm
  start_position:
  - 2000
  - 2000
  start_time: 0.0
  toa_error:
    arbitrary:
      error: 5e-9 s
      type: gaussian
    systematic:
      error: 0 s
      type: constant
  velocity:
  - 25
  - 10
