radars:
- frequency_params:
    frequency: 15000000000.0
    frequency_pattern:
    - 15000000000.0
    jitter_percentage: 5.0
    mean_frequency: 15000000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar1
  power: 1000.0
  pri_params:
    jitter_percentage: 5.0
    mean_pri: 0.001
    pri: 0.001
    pri_pattern:
    - 0.001
    repetitions:
    - 1
  pri_type: switched
  pulse_width_params:
    jitter_percentage: 4.5
    mean_pulse_width: 1.2e-06
    pulse_width: 1.0e-06
  pulse_width_type: fixed
  rotation_params:
    A: 0.1
    T_rot: 2.5
    alpha0: 0.0
    phi0: 0.0
    s: 1.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 9400000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar2
  power: 1000.0
  pri_params:
    jitter_percentage: 5.0
    mean_pri: 0.001
    pri_pattern:
    - 0.001
    - 0.0012
    - 0.0011
    - 0.0013
    repetitions:
    - 1
  pri_type: switched
  pulse_width_params:
    pulse_width: 1.8e-06
  pulse_width_type: fixed
  rotation_params:
    A: 0.1
    T_rot: 3.0
    alpha0: 0.0
    phi0: 0.0
    s: 0.5
    t0: 0.0
  rotation_type: varying
  start_position:
  - 1000
  - 1000
  start_time: 0.0
  velocity:
  - 0
  - 0
scenario:
  end_time: 10.0
  start_time: 0.0
  time_step: 0.01
sensors:
- amplitude_error:
    arbitrary:
      error: 1.5 dB
      type: uniform
    systematic:
      error: 0 dB
      type: constant
  aoa_error:
    arbitrary:
      error: 10 deg
      type: gaussian
    systematic:
      error: 0 deg
      type: constant
  detection_probability:
    level:
    - -80
    - -90
    - -95
    - -100
    probability:
    - 100
    - 80
    - 30
    - 5
  frequency_error:
    arbitrary:
      error: 10e6 Hz
      type: gaussian
    systematic:
      error: 0 Hz
      type: constant
  name: Sensor1
  pulse_width_error:
    arbitrary:
      error: 4.5%
      type: uniform
    systematic:
      error: 0 s
      type: constant
  saturation_level: -70 dB
  start_position:
  - 500
  - 500
  start_time: 2
  toa_error:
    arbitrary:
      error: 1e-9 s
      type: gaussian
    systematic:
      error: 0 s
      type: constant
  velocity:
  - -5
  - 0
- amplitude_error:
    arbitrary:
      error: 0.02 dB
      type: gaussian
    systematic:
      error: 0 dB
      rate: 0.1 dB/s
      type: linear
  aoa_error:
    arbitrary:
      error: 0.05 deg
      type: gaussian
    systematic:
      error: 0 deg
      type: constant
  detection_probability:
    level:
    - -85
    - -90
    - -95
    - -100
    probability:
    - 100
    - 80
    - 50
    - 10
  frequency_error:
    arbitrary:
      error: 5e5 Hz
      type: gaussian
    systematic:
      error: 0 Hz
      type: constant
  name: Sensor2
  pulse_width_error:
    arbitrary:
      error: 5e-9 s
      type: gaussian
    systematic:
      error: 0 s
      type: constant
  saturation_level: -70 dB
  start_position:
  - 1500
  - 1500
  start_time: 0
  toa_error:
    arbitrary:
      error: 5e-10 s
      type: gaussian
    systematic:
      error: 0 s
      type: constant
  velocity:
  - 0
  - 0
