radars:
- frequency_params:
    frequency: 15000000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar1
  power: 1000.0
  pri_params:
    pri: 0.001
  pri_type: fixed
  pulse_width_params:
    pulse_width: 1.0e-06
  pulse_width_type: fixed
  rotation_params:
    T_rot: 2.5
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
- frequency_params:
    frequency: 15000000000.0
  frequency_type: fixed
  lobe_pattern:
    main_lobe_opening_angle: 5.0
    radar_power_at_back_lobe: -20.0
    radar_power_at_main_lobe: 0.0
    type: Sinc
  name: Radar2
  power: 1000.0
  pri_params:
    pri: 0.001
  pri_type: fixed
  pulse_width_params:
    pulse_width: 1.0e-06
  pulse_width_type: fixed
  rotation_params:
    T_rot: 2.5
    alpha0: 0.0
    t0: 0.0
  rotation_type: constant
  start_position:
  - 0
  - 0
  start_time: 0.0
  velocity:
  - 0
  - 0
scenario:
  end_time: 10.0
  start_time: 0.0
  time_step: 0.1
sensors:
- amplitude_error:
    arbitrary:
      error: '0'
      type: gaussian
    systematic:
      error: '0'
      type: constant
  aoa_error:
    arbitrary:
      error: '0'
      type: gaussian
    systematic:
      error: '0'
      type: constant
  detection_probability:
    level: []
    probability: []
  frequency_error:
    arbitrary:
      error: '0'
      type: gaussian
    systematic:
      error: '0'
      type: constant
  name: Sensor1
  pulse_width_error:
    arbitrary:
      error: '0'
      type: gaussian
    systematic:
      error: '0'
      type: constant
  saturation_level: -70 dB
  start_position:
  - 0
  - 0
  start_time: 0.0
  toa_error:
    arbitrary:
      error: '0'
      type: gaussian
    systematic:
      error: '0'
      type: constant
  velocity:
  - 0
  - 0
